
repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest(unit tests)
        entry: D://LLMOPS Industry Projects/document_portal/venv/Scripts/python.exe -m pytest -q -v tests/
        language: system
        pass_filenames: false