repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Pytest for all stages
        entry: pytest tests/
        language: system
        types: [python]
        stages: [commit, push]
        pass_filenames: false
        always_run: true